Repository gamemuncheol/gamemuncheol-api, pull requests merged in 2024-06, with the labels that each got.

#119 DB 네이밍 컨벤션 변경
  src/main/java/com/gamemoonchul/domain/entity/Comment.java
  src/main/java/com/gamemoonchul/domain/entity/Member.java
  src/main/java/com/gamemoonchul/domain/entity/Post.java
  src/main/java/com/gamemoonchul/domain/entity/VoteOptions.java
  src/main/java/com/gamemoonchul/domain/entity/base/BaseTimeEntity.java
  src/main/java/com/gamemoonchul/domain/entity/riot/MatchGame.java
  src/main/java/com/gamemoonchul/domain/entity/riot/MatchUser.java
  src/main/java/com/gamemoonchul/infrastructure/repository/PostRepository.java
  src/main/java/com/gamemoonchul/infrastructure/web/CommentApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/FileUploadController.java
  src/main/java/com/gamemoonchul/infrastructure/web/MemberApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/MemberOpenApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/PostApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/PostOpenApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/RiotApiController.java
Labels: 🔨 Refactor

#120 fix: 컨벤션 변경으로 인한 테스트 에러 수정
  src/main/java/com/gamemoonchul/infrastructure/repository/impl/CommentRepositoryImpl.java
  src/test/java/com/gamemoonchul/infrastructure/web/MemberApiControllerTest.java
  src/test/java/com/gamemoonchul/infrastructure/web/MemberOpenApiControllerTest.java
Labels: 🐞 BugFix

#89 Hot 게시글 조회 구현
  src/main/java/com/gamemoonchul/application/PostOpenApiService.java
  src/main/java/com/gamemoonchul/application/converter/JsonStringListConverter.java
  src/main/java/com/gamemoonchul/domain/entity/Post.java
  src/main/java/com/gamemoonchul/infrastructure/repository/PostRepository.java
  src/main/java/com/gamemoonchul/infrastructure/web/PostOpenApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/PostMainResponse.java
  src/test/java/com/gamemoonchul/application/PostOpenApiServiceUnitTest.java
  src/test/java/com/gamemoonchul/domain/entity/PostDummy.java
  src/test/java/com/gamemoonchul/domain/entity/VoteOptionsDummy.java
Labels: ✨ Feat, 📬 Back-End, ✅ Test

#132 유저 신규 등록시 닉네임까지 등록하도록 변경
  src/main/java/com/gamemoonchul/MemberOpenApiService.java
  src/main/java/com/gamemoonchul/application/MemberService.java
  src/main/java/com/gamemoonchul/domain/entity/Member.java
  src/main/java/com/gamemoonchul/domain/entity/VoteOptions.java
  src/main/java/com/gamemoonchul/domain/entity/redis/RedisMember.java
  src/main/java/com/gamemoonchul/infrastructure/repository/MemberRepository.java
  src/main/java/com/gamemoonchul/infrastructure/web/MemberApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/MemberOpenApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/RegisterRequest.java
  src/test/java/com/gamemoonchul/application/MemberServiceTest.java
  src/test/java/com/gamemoonchul/infrastructure/web/MemberOpenApiServiceTest.java
Labels: 🎨 Modify, ✅ Test

#136 테스트 코드 dev.env(환경설정) 의존성 제거
  aws.build.gradle
  build.gradle
  src/main/java/com/gamemoonchul/application/MatchGameService.java
  src/main/java/com/gamemoonchul/application/S3Service.java
  src/test/java/com/gamemoonchul/TestDataBase.java
  src/test/java/com/gamemoonchul/application/RiotApiServiceTest.java
  src/test/java/com/gamemoonchul/application/S3ImageUploadServiceTest.java
  src/test/java/com/gamemoonchul/application/S3VideoUploadServiceTest.java
  src/test/java/com/gamemoonchul/domain/model/vo/riot/MetadataDummy.java
  src/test/java/com/gamemoonchul/infrastructure/adapter/RiotApiAdapterTest.java
  src/test/resources/application.yaml
Labels: 🔨 Refactor, ✅ Test

#135 Nickname Validation 추가
  src/main/java/com/gamemoonchul/MemberOpenApiService.java
  src/main/java/com/gamemoonchul/application/MemberService.java
  src/main/java/com/gamemoonchul/application/converter/MemberConverter.java
  src/main/java/com/gamemoonchul/common/handler/ApiExceptionHandler.java
  src/main/java/com/gamemoonchul/domain/enums/MemberRole.java
  src/main/java/com/gamemoonchul/infrastructure/web/MemberPrivacyController.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/RegisterRequest.java
  src/test/java/com/gamemoonchul/domain/entity/MemberDummy.java
  src/test/java/com/gamemoonchul/infrastructure/web/MemberPrivacyControllerTest.java
Labels: ✨ Feat

#143 회원 탈퇴 구현
  .github/workflows/cd-wordflow.yml
  src/main/java/com/gamemoonchul/config/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/gamemoonchul/config/oauth/user/AppleOAuth2UserInfo.java
  src/main/java/com/gamemoonchul/config/oauth/user/AppleUnlinkService.java
  src/main/java/com/gamemoonchul/config/oauth/user/OAuth2UserUnlinkManager.java
  src/main/java/com/gamemoonchul/domain/status/Oauth2Status.java
Labels: ✨ Feat

#146 회원 탈퇴시 Post 및 댓글 삭제될 수 있도록 변경
  src/main/java/com/gamemoonchul/MemberOpenApiService.java
  src/main/java/com/gamemoonchul/application/converter/PostConverter.java
  src/main/java/com/gamemoonchul/application/member/MemberConverter.java
  src/main/java/com/gamemoonchul/application/member/MemberDeactivateService.java
  src/main/java/com/gamemoonchul/application/member/MemberService.java
  src/main/java/com/gamemoonchul/common/handler/ApiExceptionHandler.java
  src/main/java/com/gamemoonchul/config/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/gamemoonchul/domain/entity/Post.java
  src/main/java/com/gamemoonchul/infrastructure/repository/CommentRepository.java
  src/main/java/com/gamemoonchul/infrastructure/repository/PostRepository.java
  src/main/java/com/gamemoonchul/infrastructure/repository/VoteRepository.java
  src/main/java/com/gamemoonchul/infrastructure/web/MemberApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/PostResponseDto.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/RegisterRequest.java
  src/test/java/com/gamemoonchul/application/MemberServiceTest.java
  src/test/java/com/gamemoonchul/application/member/MemberDeactivateServiceTest.java
Labels: ✨ Feat, 🐞 BugFix, ✅ Test

#144 메인화면 Hot 기능 추가
  src/main/java/com/gamemoonchul/MemberOpenApiService.java
  src/main/java/com/gamemoonchul/application/CommentService.java
  src/main/java/com/gamemoonchul/application/PostOpenApiService.java
  src/main/java/com/gamemoonchul/application/PostService.java
  src/main/java/com/gamemoonchul/application/RiotApiService.java
  src/main/java/com/gamemoonchul/application/converter/CommentConverter.java
  src/main/java/com/gamemoonchul/application/converter/PostConverter.java
  src/main/java/com/gamemoonchul/application/member/MemberConverter.java
  src/main/java/com/gamemoonchul/application/member/MemberService.java
  src/main/java/com/gamemoonchul/domain/entity/Post.java
  src/main/java/com/gamemoonchul/domain/model/dto/CommentSaveDto.java
  src/main/java/com/gamemoonchul/infrastructure/repository/PostRepository.java
  src/main/java/com/gamemoonchul/infrastructure/web/CommentApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/MemberApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/MemberOpenApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/PostApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/PostOpenApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/RiotApiController.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/request/AppleSignUpRequestDto.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/request/CommentFixRequest.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/request/CommentRequest.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/request/PostUploadRequest.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/request/RegisterRequest.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/request/RenewRequest.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/response/MatchGameResponse.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/response/MemberResponseDto.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/response/PostMainPageResponse.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/response/PostResponseDto.java
  src/main/java/com/gamemoonchul/infrastructure/web/dto/response/VoteOptionDetail.java
  src/test/java/com/gamemoonchul/application/CommentServiceTest.java
  src/test/java/com/gamemoonchul/application/PostServiceTest.java
  src/test/java/com/gamemoonchul/application/RiotApiServiceTest.java
  src/test/java/com/gamemoonchul/domain/entity/CommentDummy.java
  src/test/java/com/gamemoonchul/domain/entity/PostDummy.java
  src/test/java/com/gamemoonchul/infrastructure/web/MemberOpenApiControllerTest.java
  src/test/java/com/gamemoonchul/infrastructure/web/MemberOpenApiServiceTest.java
  src/test/java/com/gamemoonchul/infrastructure/web/dto/MatchGameResponseTest.java
Labels: ✨ Feat, 🔨 Refactor
